name: CD Pipeline (EKS + ArgoCD + Deploy)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: my-cluster
  REPO_URL: https://github.com/ayanraaz12345/my-app-manifest.git

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 🔹 1. Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 🔐 2. AWS Login (OIDC)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::961641296773:role/OIDC_Raj
          aws-region: ${{ env.AWS_REGION }}

      # 🔧 3. Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # 🔗 4. Connect to EKS (IMPORTANT)
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      # 📦 5. Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # 🚀 6. Install ArgoCD
      - name: Install ArgoCD
        run: |
          kubectl create namespace argocd || true

          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd

      # ⏳ 7. Wait for ArgoCD
      - name: Wait for ArgoCD
        run: |
          kubectl wait --for=condition=Ready pods --all -n argocd --timeout=600s

      # 🔥 8. Create ArgoCD Application
      - name: Create ArgoCD App
        run: |
          kubectl apply -f - <<EOF
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: my-app
            namespace: argocd
          spec:
            project: default
            source:
              repoURL: $REPO_URL
              targetRevision: HEAD
              path: .
            destination:
              server: https://kubernetes.default.svc
              namespace: default
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
          EOF

      # 🌍 9. Expose App (LoadBalancer)
      - name: Expose App
        run: |
          kubectl patch svc my-app-service \
          -p '{"spec": {"type": "LoadBalancer"}}' || true

      # 📡 10. Get URLs
      - name: Show URLs
        run: |
          echo "===== ArgoCD URL ====="
          kubectl get svc argocd-server -n argocd

          echo "===== App URL ====="
          kubectl get svc my-app-service
